<?php 
session_start();
?>


<script> 

	var discar;	
	var nomeContato ="<?php echo $_SESSION["user_nome"]; ?>";
	var RAMAL = "<?php echo $_SESSION["user_ramal"]; ?>";


	//disca quando clica no numero
	$(document).on('click','.discar_numero',function(){
		discar = $(this).attr('numero');
		_discar();
	});

	// função para discar
	function _discar(){
		$.post("http://192.168.86.253/lisintegra.php",{
			"acao":"discar",
			"src":RAMAL,
			"dst":discar,
			"key":123
		});
	}

	// disca quando recarrega a pagina 

	// $(document).ready(function(){
	// 	discar = $("#Telefone").attr('numero');
	// 	_discar();
	// });


$(function(){
	document.getElementById("nome2").innerHTML = nomeContato+" ("+RAMAL+")";
});
</script>

<style>
	.table td{
		padding: 0px !important;
	}

	.table input {
		width: 75%;
	}
	.p{
		padding: 0 !important;
	}
	.container-fluid{
		margin: 0;
	}

	.p-2{
		
		height:40px;

	}
	.p-3{
		
		height:35px;

	}
	.m{
		margin:0px;
	}


	.navbar {
		margin-bottom: 0px;
		/*	min-height: 40px;*/
	}



@media(min-width: 768px){
	/*	.navbar-brand{padding: 20px;}*/
	.menu1{
		/*height:40px !important;*/

		min-height: 40px;

}
.menu2{
	/*height:40px !important;*/
	min-height: 35px;


}

}

#alert_success{
	width: 200px;
    position: absolute;
    text-align: center;
    right: 0px;
    top: 24px;
    display:none;
}


</style>


<!-- menu navbar navbar-default -->
<nav class="navbar navbar-default menu1" >	


	<div class="navbar-header">
		<a class="navbar-brand p-2"  href="<?=$this->url(array('action' => "index")) ?>">Prospect</a>
	</div>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav navbar-right">
			<!-- botão do bloco de notas -->
			<li><a href="javascript:void(0)" class="p-2" title="Bloco de notas"  onclick="window.open('<?=$this->url(array('action' => "anotacao"));?>','minhaJanela','height=350,width=700')"><i class="fa fa-pencil" style="font-size: 20px;color: #4682B4"></i></a></li>

			<!-- botão de notificações pentendes-->
			<?php if ($this->line>0): ?>
				<li><a href="javascript:void(0)" class="p-2" title="Agendamentos Pendentes" data-toggle="modal" data-target="#modalPendencias" id="pendenciasProspect"><i class="fa fa-bell" style="font-size: 20px; color: orange;"></i><span class="btn-danger" style="border-radius: 7px;padding: 2px;position:relative;top: -15px;left: -6px;font-size: 11px;"><?=$this->line?></span></a></li>
			<?php endif ?>
			
			<!-- nome e ramal -->
			<li><label id="nome2" style="margin-top:14px;"></label></li>

			<!-- botão sair -->
			<?php if ($_SESSION["status_pesquisa"]==1): ?>

				<li><a href="<?= $this->url(array("action"=>"logout")) ?>" class="p-2">Sair <i class="fa fa-power-off"></i></a></li>
				
			<?php endif ?>
			
		</ul>


	</div>

</nav><!--  fim navbar navbar-default -->


<!-- menu 2  -->
<ul class="nav nav-tabs menu2">
	<li role="presentation" class="active "><a href="javascript:void(0)" class="p-3" id="btn_historico" role="tab" data-toggle="tab">Historico</a></li>
	<!-- oculta os botãos caso não aja empresa -->
	<?php if ($this->btn_cadastro==1): ?>
		<li role="presentation"><a href="javascript:void(0)" class="p-3" id="btn_cadastro" role="tab" data-toggle="tab">Cadastro</a></li>
		<!-- botão modal agendamento -->
		<li role="presentation"><a href="javascript:void(0)" class="p-3" id="btn_agendamento" role="tab" data-toggle="tab">Agendar</a></li>
	<?php endif ?>

	<!-- botão botão concluir -->
	<?php if ($this->concluir==1): ?>			


	<?php endif ?>			
</ul>
<!-- fim menu 2  -->




<div class="container" style="width: 100%;">

	<div class="row">
		<!--  div esquerda Histórico -->
		<div class="col-md-table6 col-xs-6 " style="height:570px;overflow: auto">
			
			<!-- div_historico  -->
			<div class="col-xs-12 p" id="div_historico" > 				
				<h3 class=" text-center">Histórico</h3>
				<?php if (count($this->historico)>0):?>

					<table class="table table-striped text-center" style="font-size: 12px;">
						<thead style="background-color: #ddd">
							<tr style="">
								<td rowspan="2" style="vertical-align: middle;text-align: center;"><strong>Data</strong></td>								

								<td rowspan="2" style="vertical-align: middle;text-align: center;"><strong>Campanha</strong></td>

								<td rowspan="2" style="vertical-align: middle;text-align: center;"><strong>Produto</strong></td>

								<td colspan="2" style="vertical-align: middle;text-align: center;"><strong>Status</strong></td>

								<td rowspan="2" style="vertical-align: middle;text-align: center;"><strong>Descrição</strong></td>													
							</tr>
							<tr>
								<td style=""><strong data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Sucesso">S</strong></td>
								<td style=""><strong data-toggle="popover" data-trigger="hover" data-placement="top" data-content="Interesse">I</strong></td>													
							</tr>
						</thead>
						<tbody>
							<!-- lista o historico -->
							<?php foreach ($this->historico as $key => $value): 
							$produto = $this->Produto->find($value['id_produto']);
							$campanha = $this->Campanha->find($value['id_campanha']);
							$sucesso = " ";
							$interesse = " ";

							// converte a data para o formato brasileiro
							$dataAge =$this->DataBr($value['data']);			



							if ($value['sucesso']==0) { //sucesso = 0 significa que não tem interesse
								$interesse = "<i class='fa fa-minus ' aria-hidden='true'></i>";
								$sucesso = "<i class='fa fa-times text-danger' aria-hidden='true' aria-hidden='true' data-toggle='popover' data-trigger='hover' data-placement='top' data-content='Sem Sucesso'></i>";
							}else{
								if ($value['sucesso']==1) { //sucesso = 1 significa que tem interesse
									$sucesso = "<i class='fa fa-check text-success' aria-hidden='true' aria-hidden='true' data-toggle='popover' data-trigger='hover' data-placement='top' data-content='Com Sucesso'></i>";
								}

								if ($value['interesse']==2) { //interesse = significa que tem interesse
									$interesse = "<i class='fa fa-check text-success' aria-hidden='true' data-toggle='popover' data-trigger='hover' data-placement='top' data-content='Com Interesse'></i>";
								}else{
									$interesse = "<i class='fa fa-times text-danger' aria-hidden='true' aria-hidden='true' data-toggle='popover' data-trigger='hover' data-placement='top' data-content='Sem Interesse'></i>";
								}
							}

							?>							
							
							<td width="140px" style="vertical-align: middle;"><a href="javascript:void(0)" data-toggle="popover" data-trigger="hover" data-content="<?=$value['usuario']?>"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>&nbsp;&nbsp;<?=$dataAge['datahora']?></td>
							<td style="vertical-align: middle;"><?=$campanha['nome']?></td>
							<td style="vertical-align: middle;"><?=$produto['nome']?></td>
							<td style="vertical-align: middle;"><?=$sucesso?></td>
							<td style="vertical-align: middle;"><?=$interesse?></td>								
							<td style="vertical-align: middle;max-width: 200px;"><?= $value['descricao']?></td>
						</tr>

					<?php endforeach ?>
				</tbody>
			</table>

		<?php else: ?><!-- mostrado caso não aja nem um historico -->
			<p class="text-warning text-center">Sem Registros</p>
		<?php endif ?>


		<h3 class="text-center">Agendamentos</h3>
		
		<!-- verifica se existe historico de agendamento  -->
		<?php if (count($this->historico_agendamento)>0):?>
			<table class="table table-striped text-center" style="font-size: 12px;">
				<thead style="background-color:#ddd">
					<tr>
						<td style="vertical-align: middle;text-align: center;"><strong>Data</strong></td>
						<td style="vertical-align: middle;text-align: center;"><strong>CNPJ</strong></td>
						<td style="vertical-align: middle;text-align: center;"><strong>Descrição</strong></td>
						<td></td>																	
					</tr>

				</thead>
				<tbody>

					<!-- lista todos os agendamentos  -->
					<?php

					foreach ($this->historico_agendamento as $key => $value):	
					// converte a hora pro formato brasileiro
					$dataAge = $this->DataBr($value['data']);				
					?>

					<tr>
						<td width="140px" style="vertical-align: middle;text-align: center;"><a href="javascript:void(0)" data-toggle="popover" data-trigger="hover" data-content="<?=$value['usuario']?>"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a>&nbsp;&nbsp;<?=$dataAge['datahora']?></td>
						<td style="vertical-align: middle;text-align: center;"><?=$value['cnpj_empresa']?></td>							
						<td style="vertical-align: middle;text-align: center;max-width: 200px;"><?=$value['descricao']?></td>
						
						<?php if ($value['concluido']==0): ?> <!-- caso o agendamento não esteja concluido mostra o iconi de um relagio vermelho -->
							<td style="vertical-align: middle;text-align: center;max-width: 10px;"> <i class='fa fa-clock-o text-danger' style="font-size: 16px;" aria-hidden='true' aria-hidden='true' data-toggle='popover' data-trigger='hover' data-placement='top' data-content='Agendado'></i></td>
						<?php else: ?>
							<td style="vertical-align: middle;text-align: center;max-width: 10px;"> </td>
						<?php endif ?>
					</tr>


				<?php endforeach ?>
			</tbody>
		</table>

	<?php else: ?> <!-- mostrado caso não aja nem um agendamento no historico -->
		<p class="text-warning text-center">Sem Registros</p>
	<?php endif ?>

</div><!-- fim div_historico -->



<!-- div_cadastro -->
<div id="div_cadastro" style="display: none">

	<h3 class="text-center">Cadastro</h3>
	<!-- formulario de cadastro de historico -->

	<form method="post" action="<?=$this->url(array('action' =>"historico"))?>">

		<input type="hidden" name="empresa" value="<?=$this->empresa['CNPJ']?>">
		<input type="hidden" name="idEmpresa" value="<?=$this->empresa['id_empresa']?>">
		<input type="hidden" name="campanha" value="<?=$this->user['id_campanha']?>">
		<input type="hidden" name="usuario" value="<?=$_SESSION["user_nome"]?>">

		<?php if ($this->concluir==1): ?> <!-- so é enviado se for um agendamneto -->
			<input type="hidden" name="agendamento" value="<?=$this->id_agendamento_prospect?>">			
		<?php endif ?>

		<div class="col-xs-5 p">
			<div class="form-grounp">
				<label for="produto">Produto</label>
				<select class="form-control" id="produto" name="produto">				
					<?php foreach ($this->Produto->fetch($pro) as $key => $produto): ?> <!-- exibi a lista de produtos --> 
						<option value="<?=$produto['id_produto']?>"><?=$produto['nome']?></option>
					<?php endforeach ?>				
				</select>
			</div>
		</div>

		<div class="col-xs-12 p">

			<div class="radio">
				<label><input type="radio" value="1" name="sucesso" id="com_sucesso" checked="checked">Com Sucesso</label>
				<label><input type="radio" value="0" name="sucesso" id="sem_sucesso" >Sem Sucesso</label>
			</div>


			<div class="radio" id="id_interesse">
				<strong for="">Interesse</strong>	<br>
				<label for="sim"><input type="radio" value="2" name="interesse" id="sim" checked="checked">Sim</label> <!-- valor 2 = tem interesse -->
				<label for="nao"><input type="radio" value="1" name="interesse" id="nao">Não</label> <!-- valor 1 = não tem interesse -->
			</div>

			<div class="form-grounp">			
				<label for="descricao">Descrição</label>			
				<textarea name="descricao" id="descricao" rows="3" class="form-control"></textarea>
			</div>

			<div class="form-grounp" style="padding-top: 10px">
				<button type="submit" id="historico" class="btn btn-primary pull-right">Salvar</button>	
				<button type="reset" id="historico" class="btn btn-default pull-left">Limpar</button>					

			</div>
		</div>

	</form> <!-- fim formulario de cadastro de historico -->

</div> <!-- fim div_cadastro -->




<!-- div_agendamento -->
<div id="div_agendamento" style="display: none"> 

	<h3 class="text-center">Agendamento</h3>

	<form action="<?=$this->url(array('action' =>"agendamento",'acao'=>"criar"))?>" method="post">					
		<div class="col-sm-6 p">
			<div class="form-group" >
				<label for="cnpj">CNPJ:</label>
				<input type="text" class="form-control datetime" name="mcnpj" id="mcnpj" readonly>

				<input type="hidden" name="usuario" value="<?=$this->user_nome?>">
				<input type="hidden" name="id_empresa" value="<?=$this->empresa['id_empresa']?>">

			</div>
		</div>


		<div class="col-sm-12 p">
			<div class="col-sm-6 p">
				<div class="form-gounp col-sm-6 p">
					<label for="datepicker">Data:</label>
					<input type="text" class="form-control datepicker" name="data" id="datepicker">
				</div>
				<div class="form-gounp col-sm-6 p">
					<label for="timepicker">Hora:</label>
					<input type="text" class="form-control timepicker" name="hora" id="timepicker">
				</div>
			</div>

			<div class="col-sm-12 p">
				<div class="form-group">
					<label for="descricao">Descrição:</label>
					<textarea class="form-control" rows="5" name="descricao"></textarea>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary pull-right" >Agendar</button>
				</div>
			</div>			
		</div>
	</form>
</div> <!-- fim div_agendamento -->

</div><!-- fim  div esquerda Histórico -->


<!-- div direita Dados da Empresa -->
<div class="col-sm-6">
	<h3 class="text-center">Dados da Empresa</h3>
	
	<!-- div mensagem sucesso  -->
	<div class="alert-success" id="alert_success">Salvo com Sucesso!</div>


	<form action="<?=$this->url(array('action' =>"prospect"))?>" id="update_empresa" method="post">
		<input type="hidden" name="usuario" value="<?=$this->user_nome?>">
		<input type="hidden" name="id_empresa" value="<?=$this->empresa['id_empresa']?>">		

		<table class="table table-striped" style="font-size: 14px;">
			<tbody>
				<tr>
					<td>Nome Empresa:
						<input type="text" id="NomeEmpresa" name="NomeEmpresa" style="border:0px;" value="<?=$this->empresa['NomeEmpresa']?>">
					</td>
				</tr>
				<tr>
					<td>
						Nome Fantasia:
						<input type="text" id="NomeFantasia" name="NomeFantasia" style="border:0px;" value="<?=$this->empresa['NomeFantasia']?>">
					</td>				
				</tr>
				<tr>
					<td>CNPJ:
						<input type="text" id="CNPJ" name="CNPJ" style="border:0px;" value="<?=$this->empresa['CNPJ']?>">
					</td>
				</tr>
				<tr>
					<td>Email:
						<input type="text" id="Email" name="Email" style="border:0px;" value="<?=$this->empresa['Email']?>">
					</td>

				</tr>
				<tr>
					<td>Representante:
						<input type="text" id="Representante" name="Representante" style="border:0px;" value="<?=$this->empresa['Representante']?>">
					</td>
				</tr>
				<tr>
					<td>Telefone:
						<a href="javascript:void(0)" class="discar_numero" id="Telefone" numero="<?=$this->empresa['Telefone']?>"><?=$this->empresa['Telefone']?></a>
						
					</td>
				</tr>
				<tr>
					<td>CEP:
						<input type="text" id="CEP" name="CEP" style="border:0px;" value="<?=$this->empresa['CEP']?>">
					</td>
				</tr>
				<tr>
					<td>Endereço:
						<input type="text" id="Endereco" name="Endereco" style="border:0px;" value="<?=$this->empresa['Endereco']?>">
					</td>
				</tr>
				<tr>
					<td>Numero:
						<input type="text" id="Numero" name="Numero" style="border:0px;" value="<?=$this->empresa['Numero']?>">
					</td>
				</tr>
				<tr>
					<td>Complemento:
						<input type="text" id="Complemento" name="Complemento" style="border:0px;" value="<?=$this->empresa['Complemento']?>">
					</td>
				</tr>
				<tr>
					<td>Bairro:
						<input type="text" id="Bairro" name="Bairro" style="border:0px;" value="<?=$this->empresa['Bairro']?>">
					</td>
				</tr>
				<tr>
					<td>Cidade:
						<input type="text" id="Cidade" name="Cidade" style="border:0px;" value="<?=$this->empresa['Cidade']?>">
					</td>
				</tr>
				<tr>
					<td>Estado:
						<input type="text" id="Estado" name="Estado" style="border:0px;" value="<?=$this->empresa['Estado']?>">
					</td>
				</tr>
				<tr>
					<td>Status:
						<input type="text" id="Status" name="Status" style="border:0px;" value="<?=$this->empresa['Status']?>">
					</td>
				</tr>										
				<tr>
					<td>Data Abertura:
						<input type="text" id="data_abertura" name="data_abertura" style="border:0px;" value="<?=$this->empresa['data_abertura']?>">
					</td>
				</tr>
				<tr>
					<td>Codigo Juridico:
						<input type="text" id="CodigoJuridico" name="CodigoJuridico" style="border:0px;" value="<?=$this->empresa['CodigoJuridico']?>">
					</td>
				</tr>
				<tr>
					<td>Descricao Juridica:
						<input type="text" id="DescricaoJuridica" name="DescricaoJuridica" style="border:0px;" value="<?=$this->empresa['DescricaoJuridica']?>">
					</td>				
				</tr>
			</tbody>
		</table>

		<div class=""> 
			<a href="<?=$this->url(array('action' =>"index")) ?>" class="btn btn-default pull-left">Proximo</a>
		</div>

		<div class="">
			<button type="submit" class="btn btn-primary pull-right " <?=$this->btn_disabled?>>Salvar</button>
		</div>

	</form>

</div><!-- fim div direita Dados da Empresa -->


</div> <!-- fim div row -->
</div> <!-- fim div container -->


<!-- Modal Pendencias -->
<div class="modal fade" id="modalPendencias" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="myModalLabel">Agendamentos Pendentes</h4>
			</div>
			<div class="modal-body" >					

				

				<table class="table table-striped" style="font-size: 12px;">
					<thead class="text-center">							
						<tr>
							<td><strong>Data</strong></td>
							<td><strong>CNPJ</strong></td>							
							<td><strong>Usuário</strong></td>
							<td><strong>Descrição</strong></td>
							<td><strong>Ações</strong></td>								
						</tr>

					</thead>

					<tbody class="text-center">
						<!-- lista todos os agendamentos pendentes  -->
						<?php  foreach ($this->result as  $value): 
						// converte a data para o formoto do brasil
						$dataAge =$this->DataBr($value['data']);
						?>

							<input type="hidden"  name="id" style="border:0" value="<?=$value['id_empresa']?> ">
							
							<tr>

								<td width="150">
									<?=$dataAge['datahora']?>									
								</td>							

								<td> 									
									<a href="<?=$this->url(array('action' =>"index",'edit'=>"pendencias",'id_empresa'=>$value['id_empresa'],'id_agendamento'=>$value['id_agendamento_prospect']))?>">
										<?=$value['cnpj_empresa']?>
									</a>
								</td>
								
								<td> 
									<?=$value['usuario' ]?>
								</td>

								<td style="vertical-align: middle;max-width: 200px;">
									<?= $value['descricao']?>
								</td>

								<td>											
									<button type="button" class="btn btn-xs btn-warning editar" title="Editar" data-toggle="modal" data-target="#modalEditar" edid="<?=$value['id_agendamento_prospect']?>" cnpj="<?=$value['cnpj_empresa']?>" data="<?=$dataAge['data']?>" hora="<?=$dataAge['hora']?>" descricao="<?=$value['descricao' ]?>">
										<i class="fa fa-pencil" style="font-size:12px;"></i>
									</button>																										

								</td>							
							</tr>
							

						<?php endforeach ?>
					</tbody>
				</table>


				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>

				</div>
			</div>

		</div>
	</div>
</div> <!-- fim modal pendencias -->



<!-- Modal Reagendar-->
<div class="modal fade" id="modalEditar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Reagendar</h4>
			</div>
			<div class="modal-body">

				<form action="<?=$this->url(array('action' =>"agendamento",'acao'=>"editar"))?>" method="post">
					
					<div class="form-group" >

						<label for="cnpj">CNPJ:</label>
						<input type="text" class="form-control datetime" name="mcnpj" id="edcnpj">
						<input type="hidden" name="id_empresa" value="<?=$this->empresa['id_empresa']?>">
						<input type="hidden" name="usuario" value="<?=$this->user_nome?>">

						<input type="hidden" name="id" id="edid"> 

					</div>

					<div class="form-group">

						<table >

							<tr>
								<td>
									<label for="datepicker">Data:</label>
									<input type="text" class="form-control datepicker" name="data" id="eddata">
								</td>
								<td>
									<label for="timepicker">Hora:</label>
									<input type="text" class="form-control timepicker" name="hora" id="edhora">

								</td>
							</tr>

						</table>

					</div>


					<div class="form-group">
						<label for="descricao">Descrição:</label>
						<textarea class="form-control" rows="5" name="descricao" id="eddescricao"></textarea>
					</div>

					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
						<button type="submit" class="btn btn-primary" >Agendar</button>

					</div>


				</form>

			</div>

		</div>
	</div>
</div><!--  fim modal Reagendar -->


<script type="text/javascript" src="assets/js/prospect.js"></script>


<!-- se houver notificacao -->
<?php if ($this->notificacao): 
	$notificacao = $this->notificacao; 
	//converte a data para o formato brasileiro
	$dataProspect =$this->DataBr($notificacao['data']);
	?>

<style>
	/* notificacao */
	.notificacao{
		width: 250px;
		position: fixed;
		bottom: -500px;
		right: 15px;
		border: 1px solid #a94442;
		border-radius: 4px;
		box-shadow: 0 1px 1px rgba(0,0,0,.05);
		background-color: #f2dede;
		opacity: 0.9;
	}
	.notificacao-heading{
		padding: 5px;
		border: 1px solid #a94442;
		border-bottom: 1px solid transparent;
		border-top-left-radius: 3px;
    	border-top-right-radius: 3px;
		background-color: #a94442;
		color: #fff;
	}
	.notificacao-body{
		padding: 5px;
		border: 0px solid #000;
		color: #a94442;
	}
</style>

<div class="notificacao" role="alert">
	<div class="notificacao-heading">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<i class="fa fa-times" aria-hidden="true"></i>
		</button>
		Agendamento Pendente <i class="fa fa-clock-o" aria-hidden="true"></i>
	</div>
	<div class="notificacao-body">
		<span><strong><?=$dataProspect['datahora']?></strong></span>
		<p><?=$notificacao["descricao"]?></p>
	</div>
</div>

<script>
	$(".notificacao").animate({
		bottom: '15px'
	},1000)
	$(".close").click(function(){
		$(".notificacao").fadeOut('low');
	});
</script>
 
<?php endif; ?>